/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ReportRouteImport } from './routes/report'
import { Route as TasksNmqRouteImport } from './routes/tasks.nmq'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksNmqRoute = TasksNmqRouteImport.update({
  id: '/tasks/nmq',
  path: '/tasks/nmq',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/report': typeof ReportRoute
  '/tasks/nmq': typeof TasksNmqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/report': typeof ReportRoute
  '/tasks/nmq': typeof TasksNmqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/health': typeof HealthRoute
  '/report': typeof ReportRoute
  '/tasks/nmq': typeof TasksNmqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/account' | '/health' | '/report' | '/tasks/nmq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/account' | '/health' | '/report' | '/tasks/nmq'
  id:
    '__root__' | '/' | '/$' | '/account' | '/health' | '/report' | '/tasks/nmq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  HealthRoute: typeof HealthRoute
  ReportRoute: typeof ReportRoute
  TasksNmqRoute: typeof TasksNmqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/nmq': {
      id: '/tasks/nmq'
      path: '/tasks/nmq'
      fullPath: '/tasks/nmq'
      preLoaderRoute: typeof TasksNmqRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  HealthRoute: HealthRoute,
  ReportRoute: ReportRoute,
  TasksNmqRoute: TasksNmqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
