/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EmployeeRouteImport } from './routes/_employee'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EmployeeIndexRouteImport } from './routes/_employee/index'
import { Route as EmployeeSplatRouteImport } from './routes/_employee/$'
import { Route as EmployeeAccountRouteImport } from './routes/_employee/account'
import { Route as EmployeeHealthRouteImport } from './routes/_employee/health'
import { Route as EmployeeReportRouteImport } from './routes/_employee/report'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as EmployeeTasksAcknowledgementIdRouteImport } from './routes/_employee/tasks.acknowledgement.$id'
import { Route as EmployeeTasksCbiIdRouteImport } from './routes/_employee/tasks.cbi.$id'
import { Route as EmployeeTasksNmqIdRouteImport } from './routes/_employee/tasks.nmq.$id'
import { Route as EmployeeTasksOverloadIdRouteImport } from './routes/_employee/tasks.overload.$id'

const EmployeeRoute = EmployeeRouteImport.update({
  id: '/_employee',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeIndexRoute = EmployeeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeSplatRoute = EmployeeSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeAccountRoute = EmployeeAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeHealthRoute = EmployeeHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeReportRoute = EmployeeReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => EmployeeRoute,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeTasksAcknowledgementIdRoute =
  EmployeeTasksAcknowledgementIdRouteImport.update({
    id: '/tasks/acknowledgement/$id',
    path: '/tasks/acknowledgement/$id',
    getParentRoute: () => EmployeeRoute,
  } as any)
const EmployeeTasksCbiIdRoute = EmployeeTasksCbiIdRouteImport.update({
  id: '/tasks/cbi/$id',
  path: '/tasks/cbi/$id',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTasksNmqIdRoute = EmployeeTasksNmqIdRouteImport.update({
  id: '/tasks/nmq/$id',
  path: '/tasks/nmq/$id',
  getParentRoute: () => EmployeeRoute,
} as any)
const EmployeeTasksOverloadIdRoute = EmployeeTasksOverloadIdRouteImport.update({
  id: '/tasks/overload/$id',
  path: '/tasks/overload/$id',
  getParentRoute: () => EmployeeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof EmployeeIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof EmployeeSplatRoute
  '/account': typeof EmployeeAccountRoute
  '/health': typeof EmployeeHealthRoute
  '/report': typeof EmployeeReportRoute
  '/sign/$token': typeof SignTokenRoute
  '/tasks/acknowledgement/$id': typeof EmployeeTasksAcknowledgementIdRoute
  '/tasks/cbi/$id': typeof EmployeeTasksCbiIdRoute
  '/tasks/nmq/$id': typeof EmployeeTasksNmqIdRoute
  '/tasks/overload/$id': typeof EmployeeTasksOverloadIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof EmployeeSplatRoute
  '/account': typeof EmployeeAccountRoute
  '/health': typeof EmployeeHealthRoute
  '/report': typeof EmployeeReportRoute
  '/sign/$token': typeof SignTokenRoute
  '/': typeof EmployeeIndexRoute
  '/tasks/acknowledgement/$id': typeof EmployeeTasksAcknowledgementIdRoute
  '/tasks/cbi/$id': typeof EmployeeTasksCbiIdRoute
  '/tasks/nmq/$id': typeof EmployeeTasksNmqIdRoute
  '/tasks/overload/$id': typeof EmployeeTasksOverloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_employee': typeof EmployeeRouteWithChildren
  '/login': typeof LoginRoute
  '/_employee/$': typeof EmployeeSplatRoute
  '/_employee/account': typeof EmployeeAccountRoute
  '/_employee/health': typeof EmployeeHealthRoute
  '/_employee/report': typeof EmployeeReportRoute
  '/sign/$token': typeof SignTokenRoute
  '/_employee/': typeof EmployeeIndexRoute
  '/_employee/tasks/acknowledgement/$id': typeof EmployeeTasksAcknowledgementIdRoute
  '/_employee/tasks/cbi/$id': typeof EmployeeTasksCbiIdRoute
  '/_employee/tasks/nmq/$id': typeof EmployeeTasksNmqIdRoute
  '/_employee/tasks/overload/$id': typeof EmployeeTasksOverloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/account'
    | '/health'
    | '/report'
    | '/sign/$token'
    | '/tasks/acknowledgement/$id'
    | '/tasks/cbi/$id'
    | '/tasks/nmq/$id'
    | '/tasks/overload/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/account'
    | '/health'
    | '/report'
    | '/sign/$token'
    | '/'
    | '/tasks/acknowledgement/$id'
    | '/tasks/cbi/$id'
    | '/tasks/nmq/$id'
    | '/tasks/overload/$id'
  id:
    | '__root__'
    | '/_employee'
    | '/login'
    | '/_employee/$'
    | '/_employee/account'
    | '/_employee/health'
    | '/_employee/report'
    | '/sign/$token'
    | '/_employee/'
    | '/_employee/tasks/acknowledgement/$id'
    | '/_employee/tasks/cbi/$id'
    | '/_employee/tasks/nmq/$id'
    | '/_employee/tasks/overload/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  EmployeeRoute: typeof EmployeeRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignTokenRoute: typeof SignTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_employee': {
      id: '/_employee'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee/': {
      id: '/_employee/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof EmployeeIndexRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/$': {
      id: '/_employee/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof EmployeeSplatRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/account': {
      id: '/_employee/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof EmployeeAccountRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/health': {
      id: '/_employee/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof EmployeeHealthRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/report': {
      id: '/_employee/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof EmployeeReportRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_employee/tasks/acknowledgement/$id': {
      id: '/_employee/tasks/acknowledgement/$id'
      path: '/tasks/acknowledgement/$id'
      fullPath: '/tasks/acknowledgement/$id'
      preLoaderRoute: typeof EmployeeTasksAcknowledgementIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/tasks/cbi/$id': {
      id: '/_employee/tasks/cbi/$id'
      path: '/tasks/cbi/$id'
      fullPath: '/tasks/cbi/$id'
      preLoaderRoute: typeof EmployeeTasksCbiIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/tasks/nmq/$id': {
      id: '/_employee/tasks/nmq/$id'
      path: '/tasks/nmq/$id'
      fullPath: '/tasks/nmq/$id'
      preLoaderRoute: typeof EmployeeTasksNmqIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
    '/_employee/tasks/overload/$id': {
      id: '/_employee/tasks/overload/$id'
      path: '/tasks/overload/$id'
      fullPath: '/tasks/overload/$id'
      preLoaderRoute: typeof EmployeeTasksOverloadIdRouteImport
      parentRoute: typeof EmployeeRoute
    }
  }
}

interface EmployeeRouteChildren {
  EmployeeSplatRoute: typeof EmployeeSplatRoute
  EmployeeAccountRoute: typeof EmployeeAccountRoute
  EmployeeHealthRoute: typeof EmployeeHealthRoute
  EmployeeReportRoute: typeof EmployeeReportRoute
  EmployeeIndexRoute: typeof EmployeeIndexRoute
  EmployeeTasksAcknowledgementIdRoute: typeof EmployeeTasksAcknowledgementIdRoute
  EmployeeTasksCbiIdRoute: typeof EmployeeTasksCbiIdRoute
  EmployeeTasksNmqIdRoute: typeof EmployeeTasksNmqIdRoute
  EmployeeTasksOverloadIdRoute: typeof EmployeeTasksOverloadIdRoute
}

const EmployeeRouteChildren: EmployeeRouteChildren = {
  EmployeeSplatRoute: EmployeeSplatRoute,
  EmployeeAccountRoute: EmployeeAccountRoute,
  EmployeeHealthRoute: EmployeeHealthRoute,
  EmployeeReportRoute: EmployeeReportRoute,
  EmployeeIndexRoute: EmployeeIndexRoute,
  EmployeeTasksAcknowledgementIdRoute: EmployeeTasksAcknowledgementIdRoute,
  EmployeeTasksCbiIdRoute: EmployeeTasksCbiIdRoute,
  EmployeeTasksNmqIdRoute: EmployeeTasksNmqIdRoute,
  EmployeeTasksOverloadIdRoute: EmployeeTasksOverloadIdRoute,
}

const EmployeeRouteWithChildren = EmployeeRoute._addFileChildren(
  EmployeeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  EmployeeRoute: EmployeeRouteWithChildren,
  LoginRoute: LoginRoute,
  SignTokenRoute: SignTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
