/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppCasesRouteImport } from './routes/_app/cases'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app/employees.index'
import { Route as AppEmployeesEmployeeIdRouteImport } from './routes/_app/employees.$employeeId'
import { Route as AppExamsImportRouteImport } from './routes/_app/exams.import'
import { Route as AppProgramsErgoRouteImport } from './routes/_app/programs.ergo'
import { Route as AppProgramsMaternalRouteImport } from './routes/_app/programs.maternal'
import { Route as AppProgramsNoticesRouteImport } from './routes/_app/programs.notices'
import { Route as AppProgramsViolenceRouteImport } from './routes/_app/programs.violence'
import { Route as AppProgramsWorkloadRouteImport } from './routes/_app/programs.workload'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesEmployeeIdRoute = AppEmployeesEmployeeIdRouteImport.update({
  id: '/employees/$employeeId',
  path: '/employees/$employeeId',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsImportRoute = AppExamsImportRouteImport.update({
  id: '/exams/import',
  path: '/exams/import',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsErgoRoute = AppProgramsErgoRouteImport.update({
  id: '/programs/ergo',
  path: '/programs/ergo',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsMaternalRoute = AppProgramsMaternalRouteImport.update({
  id: '/programs/maternal',
  path: '/programs/maternal',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsNoticesRoute = AppProgramsNoticesRouteImport.update({
  id: '/programs/notices',
  path: '/programs/notices',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsViolenceRoute = AppProgramsViolenceRouteImport.update({
  id: '/programs/violence',
  path: '/programs/violence',
  getParentRoute: () => AppRoute,
} as any)
const AppProgramsWorkloadRoute = AppProgramsWorkloadRouteImport.update({
  id: '/programs/workload',
  path: '/programs/workload',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/cases': typeof AppCasesRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/exams/import': typeof AppExamsImportRoute
  '/programs/ergo': typeof AppProgramsErgoRoute
  '/programs/maternal': typeof AppProgramsMaternalRoute
  '/programs/notices': typeof AppProgramsNoticesRoute
  '/programs/violence': typeof AppProgramsViolenceRoute
  '/programs/workload': typeof AppProgramsWorkloadRoute
  '/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof AppSplatRoute
  '/cases': typeof AppCasesRoute
  '/': typeof AppIndexRoute
  '/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/exams/import': typeof AppExamsImportRoute
  '/programs/ergo': typeof AppProgramsErgoRoute
  '/programs/maternal': typeof AppProgramsMaternalRoute
  '/programs/notices': typeof AppProgramsNoticesRoute
  '/programs/violence': typeof AppProgramsViolenceRoute
  '/programs/workload': typeof AppProgramsWorkloadRoute
  '/employees': typeof AppEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$': typeof AppSplatRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$employeeId': typeof AppEmployeesEmployeeIdRoute
  '/_app/exams/import': typeof AppExamsImportRoute
  '/_app/programs/ergo': typeof AppProgramsErgoRoute
  '/_app/programs/maternal': typeof AppProgramsMaternalRoute
  '/_app/programs/notices': typeof AppProgramsNoticesRoute
  '/_app/programs/violence': typeof AppProgramsViolenceRoute
  '/_app/programs/workload': typeof AppProgramsWorkloadRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/cases'
    | '/employees/$employeeId'
    | '/exams/import'
    | '/programs/ergo'
    | '/programs/maternal'
    | '/programs/notices'
    | '/programs/violence'
    | '/programs/workload'
    | '/employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/cases'
    | '/'
    | '/employees/$employeeId'
    | '/exams/import'
    | '/programs/ergo'
    | '/programs/maternal'
    | '/programs/notices'
    | '/programs/violence'
    | '/programs/workload'
    | '/employees'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$'
    | '/_app/cases'
    | '/_app/'
    | '/_app/employees/$employeeId'
    | '/_app/exams/import'
    | '/_app/programs/ergo'
    | '/_app/programs/maternal'
    | '/_app/programs/notices'
    | '/_app/programs/violence'
    | '/_app/programs/workload'
    | '/_app/employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$employeeId': {
      id: '/_app/employees/$employeeId'
      path: '/employees/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof AppEmployeesEmployeeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/import': {
      id: '/_app/exams/import'
      path: '/exams/import'
      fullPath: '/exams/import'
      preLoaderRoute: typeof AppExamsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/ergo': {
      id: '/_app/programs/ergo'
      path: '/programs/ergo'
      fullPath: '/programs/ergo'
      preLoaderRoute: typeof AppProgramsErgoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/maternal': {
      id: '/_app/programs/maternal'
      path: '/programs/maternal'
      fullPath: '/programs/maternal'
      preLoaderRoute: typeof AppProgramsMaternalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/notices': {
      id: '/_app/programs/notices'
      path: '/programs/notices'
      fullPath: '/programs/notices'
      preLoaderRoute: typeof AppProgramsNoticesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/violence': {
      id: '/_app/programs/violence'
      path: '/programs/violence'
      fullPath: '/programs/violence'
      preLoaderRoute: typeof AppProgramsViolenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/programs/workload': {
      id: '/_app/programs/workload'
      path: '/programs/workload'
      fullPath: '/programs/workload'
      preLoaderRoute: typeof AppProgramsWorkloadRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppCasesRoute: typeof AppCasesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesEmployeeIdRoute: typeof AppEmployeesEmployeeIdRoute
  AppExamsImportRoute: typeof AppExamsImportRoute
  AppProgramsErgoRoute: typeof AppProgramsErgoRoute
  AppProgramsMaternalRoute: typeof AppProgramsMaternalRoute
  AppProgramsNoticesRoute: typeof AppProgramsNoticesRoute
  AppProgramsViolenceRoute: typeof AppProgramsViolenceRoute
  AppProgramsWorkloadRoute: typeof AppProgramsWorkloadRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppCasesRoute: AppCasesRoute,
  AppIndexRoute: AppIndexRoute,
  AppEmployeesEmployeeIdRoute: AppEmployeesEmployeeIdRoute,
  AppExamsImportRoute: AppExamsImportRoute,
  AppProgramsErgoRoute: AppProgramsErgoRoute,
  AppProgramsMaternalRoute: AppProgramsMaternalRoute,
  AppProgramsNoticesRoute: AppProgramsNoticesRoute,
  AppProgramsViolenceRoute: AppProgramsViolenceRoute,
  AppProgramsWorkloadRoute: AppProgramsWorkloadRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
